### ISSUE TITLE
user tag creation

### ISSUE THREAD

**Issue by sridharrajs** [sridharrajs/ynbt#32]

**Comment by suriyadeepan** [comment]
Feature : Let users organize articles using a hierarchy. Display the whole tree using D3.js or something similar, to provide a holistic view of articles.

Example:
- Machine Learning
  - Theory
    - Reinforcement Learning
      - Alpha Go article
      - David Silver's Lecture
      - Udacity Course
  - Code
  - Datasets
- Philosophy
- Quantum Mechanics
