### ISSUE TITLE
Installation script ?

### ISSUE THREAD

**Issue by fly-man-** [sridharrajs/ynbt#58]
I've been trying to get this to work on a development machine but so far, each time I'm getting timeout errors or even messages like:

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

Is it possible for you to write a installation script that just installs everything the basic way, on a clean Ubuntu 16.04 version ?

**Comment by sridharrajs** [comment]
I've updated the README.md with the better installation instructions on how to set your local dev environment. Check that out.

**Comment by sridharrajs** [comment]
Node server is up but #60 is causing the UI to a show blank page after logging in. Working on that.

**Comment by sridharrajs** [comment]
This is now fixed! Pull for changes
