### ISSUE TITLE
Error when trying to install admin user

### ISSUE THREAD

**Issue by fly-man-** [sridharrajs/ynbt#61]
When issuing "node bin/install.js"

Installation failed Error: HOST_ENV isn't set

Where do  I set this and why doesn't the installation script do it for me ?

**Comment by sridharrajs** [comment]
Thanks for pointing that. The idea I'd was, to have an [environment agnostic code base](http://www.hacksparrow.com/running-express-js-in-production-mode.html) without any hard coded values. I've updated the README.md with the missing details on how to set environment variable.
