### ISSUE TITLE
Content not refreshed until page reload

### ISSUE THREAD

**Issue by mariadanieldeepak** [sridharrajs/ynbt#77]
After adding a valid URL, the count in the Unread menu and the URL snippet content listed are not updated until page reload.

This happened when I was in the page `http://yabt.sridhar.co/#/unreads` and tried adding an URL.

**Comment by sridharrajs** [comment]
The expected behavior is the new url should be added at the beginning of the list.

**Comment by mariadanieldeepak** [comment]
Cool, thanks.
